language: python
python:
 - "2.7"
 
install: 
 - pip install requests

# command to run tests
script:
 - cd "HW02"
 - python -m unittest TestTriangle
 - cd ..
 - cd "HW04a"
 - python -m unittest HW04aTest
